# Site Settings
title: Distributed AI for dependable cyberSecuritY
tagline: Research Unit in Fondazione Bruno Kessler (FBK)
remote_theme: csfbk/fbk-cs-websites-theme
repository: daisyfbk/daisyfbk.github.io

# Entity Settings
entity_type: "unit"

organization:
  unit:
    name: "Distributed AI for dependable cyberSecuritY"
    acronym: "DAISY"
  center:
    name: "Center for Cybersecurity"
    acronym: "CS"
    website: "https://cs.fbk.eu"

logos:
  unit:
    regular:
      default: "/assets/images/institutional/DAISY_regular.png"
      white: "/assets/images/institutional/DAISY_regular_white.png"
    symbol:
      default: "/assets/images/institutional/DAISY_symbol.png"
      white: "/assets/images/institutional/DAISY_symbol_white.png"

content-manager:
  name: Roberto Doriguzzi Corin
  affiliation: Center for Cybersecurity
  email: rdoriguzzi@fbk.eu
  phone: "+390461312429"

social:
  github: https://github.com/daisyfbk/

# Other Settings and Defaults
livereload: true
primary-color: "#0068b4"

## DO NOT MODIFY
lang: en
baseurl: ""
permalink: pretty
markdown: kramdown
highlighter: rouge
show_navbar_brand: false
show_link_fbk: true
sass:
  style: compressed
  source_dir: _sass

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

collections:
  collaborations:
    output: true
    layout: collaboration
  complementary:
    output: true
    layout: complementary
  events:
    output: true
    layout: page
  news:
    output: true
    layout: news
    permalink: /news/:year/:month/:day/:title/
  people:
    output: true
    layout: page
  projects:
    output: true
    layout: project
  teaching:
    output: true
    layout: page
  tools:
    output: true
    layout: tool
  topics:
    output: true
    layout: topic

defaults:
  - scope:
      path: ""
      type: pages
    values:
      show_sidebar: false

  - scope:
      type: collaborations
    values:
      layout: collaboration

  - scope:
      type: complementary
    values:
      layout: complementary

  - scope:
      type: events
    values:
      layout: page

  - scope:
      type: news
    values:
      layout: news

  - scope:
      path: "_people/*-*"
    values:
      layout: person

  - scope:
      path: "_people/archive/*-*"
    values:
      layout: person

  - scope:
      type: projects
    values:
      layout: project

  - scope:
      type: tools
    values:
      layout: tool

  - scope:
      type: topics
    values:
      layout: topic

exclude: [
  "Gemfile",
  "clean-theme.gemspec",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "*/template*.md",
  "*/_template*.md",
  "README*.md"
]